import axios from 'axios'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Card } from '../components/Card'

interface AnnouncementsProperties {
  id: number,
  link?: string,
  title?: string,
  content?: string,
  date?: string
}

type Announcements = {
  announcements: AnnouncementsProperties[]
}

const Home: NextPage<Announcements> = ({ announcements }: Announcements) => {

  return (
    <div>
      <Head>
        <title>Currency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div
        className='container mx-auto text-center mt-16'
      >
        <h1 className='text-5xl font-mono font-bold'>
          Anúncios sobre o mercado de cripto moedas.
        </h1>

        <div className='grid grid-cols-3 mt-8'>
          {
            announcements.map(announcement => {
              return (
                <Card 
                  title={announcement.title ?? ''}
                  key={announcement.id}
                  preview={announcement.content ? announcement.content?.replaceAll(/(&nbsp;|<([^>]+)>)/ig, '') : ''}
                  href={`/${announcement.id}`}
                />
              )
            })
          }
        </div>

      </div>

    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {

  const response_announcement = await axios.get('https://www.bitmex.com/api/v1/announcement')
  const response_urgent_announcement = await axios.get('https://www.bitmex.com/api/v1/announcement/urgent')
  const { data: urgent_announcement } = response_urgent_announcement
  const { data: announcement } = response_announcement
  
  const announcements = [...urgent_announcement, ...announcement]

  return {
    props: { announcements }
  }
}